from __future__ import annotations

import math
from dataclasses import dataclass

from .data import LABEL_AI, LABEL_HUMAN
from .ollama_client import OllamaClient, UnparseableResponse


YES_TOKENS = ("Yes", "yes", " Yes", "YES", " yes")
NO_TOKENS = ("No", "no", " No", "NO", " no")


def _best_logprob(logprobs: dict[str, float], keys: tuple[str, ...]) -> float | None:
    hits = [logprobs[k] for k in keys if k in logprobs]
    return max(hits) if hits else None


def yes_no_prob_ai(logprobs: dict[str, float] | None) -> float | None:
    """Uncalibrated P(AI) from top-token {Yes,No} logprobs via 2-way softmax.

    Returns None if neither Yes nor No is in the top-k candidates.
    """
    if not logprobs:
        return None
    lp_yes = _best_logprob(logprobs, YES_TOKENS)
    lp_no = _best_logprob(logprobs, NO_TOKENS)
    if lp_yes is None and lp_no is None:
        return None
    if lp_yes is None:
        return 0.0
    if lp_no is None:
        return 1.0
    m = max(lp_yes, lp_no)
    eyes = math.exp(lp_yes - m)
    enos = math.exp(lp_no - m)
    return eyes / (eyes + enos)


PROMPT_TEMPLATE = """You are a text-origin classifier. Decide whether the passage below was written by a human or generated by an AI language model.

Passage:
\"\"\"
{text}
\"\"\"

Respond with exactly one word: "Yes" if it was AI-generated, "No" if it was written by a human. Do not explain.
Answer:"""


@dataclass
class Prediction:
    label: int
    raw_response: str
    prompt_version: str = "v1"
    logprobs: dict[str, float] | None = None


def build_prompt(text: str) -> str:
    return PROMPT_TEMPLATE.format(text=text.strip())


def parse_yes_no(response: str) -> int:
    token = response.strip().lower().lstrip('"').lstrip("'").split()[0] if response.strip() else ""
    if token.startswith("yes"):
        return LABEL_AI
    if token.startswith("no"):
        return LABEL_HUMAN
    raise UnparseableResponse(f"Could not parse yes/no from: {response!r}")


def classify(
    client: OllamaClient,
    text: str,
    num_predict: int = 16,
    temperature: float = 0.0,
    think: bool = False,
    system_prompt: str | None = None,
    return_logprobs: bool = False,
    top_logprobs_k: int = 10,
    keep_alive: str | int | None = "1h",
    num_ctx: int | None = None,
    num_batch: int | None = None,
) -> Prediction:
    prompt = build_prompt(text)
    result = client.generate(
        prompt,
        num_predict=num_predict,
        temperature=temperature,
        think=think,
        system=system_prompt,
        return_logprobs=return_logprobs,
        top_logprobs_k=top_logprobs_k,
        keep_alive=keep_alive,
        num_ctx=num_ctx,
        num_batch=num_batch,
    )
    label = parse_yes_no(result.text)
    return Prediction(label=label, raw_response=result.text, logprobs=result.logprobs)
