from __future__ import annotations

from dataclasses import dataclass

from .data import LABEL_AI, LABEL_HUMAN
from .ollama_client import OllamaClient, UnparseableResponse


PROMPT_TEMPLATE = """You are a text-origin classifier. Decide whether the passage below was written by a human or generated by an AI language model.

Passage:
\"\"\"
{text}
\"\"\"

Respond with exactly one word: "Yes" if it was AI-generated, "No" if it was written by a human. Do not explain.
Answer:"""


@dataclass
class Prediction:
    label: int
    raw_response: str
    prompt_version: str = "v1"
    logprobs: dict[str, float] | None = None


def build_prompt(text: str) -> str:
    return PROMPT_TEMPLATE.format(text=text.strip())


def parse_yes_no(response: str) -> int:
    token = response.strip().lower().lstrip('"').lstrip("'").split()[0] if response.strip() else ""
    if token.startswith("yes"):
        return LABEL_AI
    if token.startswith("no"):
        return LABEL_HUMAN
    raise UnparseableResponse(f"Could not parse yes/no from: {response!r}")


def classify(
    client: OllamaClient,
    text: str,
    num_predict: int = 16,
    temperature: float = 0.0,
    think: bool = False,
    system_prompt: str | None = None,
    return_logprobs: bool = False,
) -> Prediction:
    if return_logprobs:
        raise NotImplementedError("Thread A: logprob extraction path not yet wired up")
    prompt = build_prompt(text)
    result = client.generate(
        prompt,
        num_predict=num_predict,
        temperature=temperature,
        think=think,
        system=system_prompt,
    )
    label = parse_yes_no(result.text)
    return Prediction(label=label, raw_response=result.text)
