from __future__ import annotations

import argparse
import datetime as dt
import json
import pathlib
import re
import sys
from dataclasses import asdict, dataclass

import yaml
from rich.console import Console

from .classifier import classify
from .data import LABEL_AI, LABEL_HUMAN, Example, load_hc3, make_splits, splits_sha256
from .ollama_client import OllamaClient, UnparseableResponse
from .plots import plot_trajectory
from .run import RUNS_DIR, RUNS_LOG, _mint_run_id, _setup_logger

POLICIES_DIR = pathlib.Path(__file__).resolve().parents[3] / "logs" / "policies"
_POLICY_TAG = re.compile(r"<policy>\s*(.*?)\s*</policy>", re.DOTALL)
_EXAMPLE_TRUNC = 400

PROPOSE_INITIAL_TEMPLATE = """You are designing a concise natural-language policy to help a classifier decide whether a passage was written by a human or generated by an AI language model.

Study the labeled examples below, then produce a policy the classifier will use as a system prompt when reading new passages.

Requirements:
- Free-flowing prose. No numbered rules, no JSON.
- Soft cap: ~20 lines.
- Describe concrete linguistic, structural, or content signals you see in the data.
- Do NOT restate that the task is AI-vs-human classification.
- The classifier will answer "Yes" (AI) or "No" (human); your policy must help it choose.

Labeled examples ({n}):
{examples}

Output ONLY the policy, wrapped in <policy>...</policy> tags. No commentary before or after."""

REFINE_TEMPLATE = """You are refining a natural-language policy used by a text-origin classifier (Yes=AI, No=human).

Current policy (F0.5={f0_5:.3f} on validation):
<policy>
{policy}
</policy>

Below are examples the classifier currently misclassifies under this policy. Revise the policy so it handles these cases correctly, while keeping the signals that already work.

Requirements:
- Keep the policy ~20 lines of prose; do not let it balloon.
- Do NOT copy examples verbatim into the policy.

Misclassified examples:
{examples}

Output ONLY the revised policy, wrapped in <policy>...</policy> tags."""

@dataclass
class PolicyScore:
    f0_5: float
    precision_ai: float
    recall_ai: float
    per_class: dict[str, int]
    hard_preds: list[int]

@dataclass
class Iteration:
    iter: int
    policy_text: str
    f0_5: float
    precision_ai: float
    recall_ai: float
    accepted: bool
    parent_iter: int | None

def _format_examples_block(examples: list[Example]) -> str:
    lines: list[str] = []
    for i, ex in enumerate(examples, 1):
        label = "AI" if ex.label == LABEL_AI else "human"
        snippet = ex.text.strip().replace("\n", " ")
        if len(snippet) > _EXAMPLE_TRUNC:
            snippet = snippet[:_EXAMPLE_TRUNC].rstrip() + "…"
        lines.append(f'Example {i} (label={label}): "{snippet}"')
    return "\n\n".join(lines)

def _extract_policy(text: str) -> str:
    m = _POLICY_TAG.search(text)
    if not m or not m.group(1).strip():
        raise UnparseableResponse(f"No usable <policy> block in: {text[:200]!r}")
    return m.group(1).strip()

def _f_beta(labels: list[int], preds: list[int], beta: float = 0.5) -> tuple[float, float, float]:
    tp = fp = fn = 0
    for y, p in zip(labels, preds):
        if p == -1: continue
        if p == LABEL_AI and y == LABEL_AI: tp += 1
        elif p == LABEL_AI and y == LABEL_HUMAN: fp += 1
        elif p == LABEL_HUMAN and y == LABEL_AI: fn += 1
    precision = tp / (tp + fp) if (tp + fp) else 0.0
    recall = tp / (tp + fn) if (tp + fn) else 0.0
    denom = (beta * beta * precision) + recall
    f = ((1 + beta * beta) * precision * recall / denom) if denom else 0.0
    return f, precision, recall

def _find_misclassified(examples: list[Example], hard_preds: list[int], k: int) -> list[Example]:
    fps = [e for e, p in zip(examples, hard_preds) if p == LABEL_AI and e.label == LABEL_HUMAN]
    fns = [e for e, p in zip(examples, hard_preds) if p == LABEL_HUMAN and e.label == LABEL_AI]
    half = k // 2
    return (fps[:half] + fns[: k - half] + fps[half:] + fns[k - half:])[:k]

def propose_initial(client: OllamaClient, labeled_examples: list[Example], *, num_predict: int = 512, temperature: float = 0.0) -> str:
    prompt = PROPOSE_INITIAL_TEMPLATE.format(n=len(labeled_examples), examples=_format_examples_block(labeled_examples))
    return _extract_policy(client.generate(prompt, num_predict=num_predict, temperature=temperature).text)

def score_policy(client: OllamaClient, policy: str, examples: list[Example], *, num_predict: int = 16, temperature: float = 0.0) -> PolicyScore:
    preds: list[int] = []
    for ex in examples:
        try:
            preds.append(classify(client, ex.text, num_predict=num_predict, temperature=temperature, system_prompt=policy).label)
        except UnparseableResponse:
            preds.append(-1)
    labels = [e.label for e in examples]
    f0_5, prec, rec = _f_beta(labels, preds, beta=0.5)
    per_class = {"yes": sum(1 for p in preds if p == LABEL_AI), "no": sum(1 for p in preds if p == LABEL_HUMAN), "other": sum(1 for p in preds if p == -1)}
    return PolicyScore(f0_5=f0_5, precision_ai=prec, recall_ai=rec, per_class=per_class, hard_preds=preds)

def refine(client: OllamaClient, current_policy: str, misclassified: list[Example], *, current_f0_5: float = 0.0, num_predict: int = 512, temperature: float = 0.0) -> str:
    prompt = REFINE_TEMPLATE.format(policy=current_policy, f0_5=current_f0_5, examples=_format_examples_block(misclassified))
    return _extract_policy(client.generate(prompt, num_predict=num_predict, temperature=temperature).text)

def induce(client: OllamaClient, seed_examples: list[Example], val_examples: list[Example], *, max_iters: int = 30, plateau_threshold: float = 0.005, plateau_window: int = 3, misclassified_k: int = 20, max_consecutive_rejections: int = 5, trajectory_file: pathlib.Path | None = None, logger=None) -> list[Iteration]:
    log = (lambda m: logger.info(m)) if logger is not None else (lambda m: None)
    traj_fh = trajectory_file.open("w") if trajectory_file is not None else None
    def _emit(step: Iteration) -> None:
        traj.append(step)
        if traj_fh is not None:
            traj_fh.write(json.dumps(asdict(step), ensure_ascii=False) + "\n")
            traj_fh.flush()
    traj: list[Iteration] = []
    try:
        policy0 = propose_initial(client, seed_examples)
        s0 = score_policy(client, policy0, val_examples)
        _emit(Iteration(0, policy0, s0.f0_5, s0.precision_ai, s0.recall_ai, True, None))
        log(f"iter=0 F0.5={s0.f0_5:.3f} P={s0.precision_ai:.3f} R={s0.recall_ai:.3f} (initial)")
        best, best_hard, recent = traj[0], s0.hard_preds, [s0.f0_5]
        consecutive_rej = 0
        for it in range(1, max_iters + 1):
            miscls = _find_misclassified(val_examples, best_hard, misclassified_k)
            if not miscls:
                log(f"iter={it} no misclassified examples; stopping"); break
            try:
                candidate = refine(client, best.policy_text, miscls, current_f0_5=best.f0_5)
            except UnparseableResponse as e:
                log(f"iter={it} refine failed: {e}; stopping"); break
            sc = score_policy(client, candidate, val_examples)
            accepted = sc.f0_5 > best.f0_5
            _emit(Iteration(it, candidate, sc.f0_5, sc.precision_ai, sc.recall_ai, accepted, best.iter))
            log(f"iter={it} F0.5={sc.f0_5:.3f} ({'accepted' if accepted else 'rejected'})")
            if accepted:
                best, best_hard, consecutive_rej = traj[-1], sc.hard_preds, 0
                recent.append(sc.f0_5)
                window = recent[-plateau_window:]
                if len(window) == plateau_window and (max(window) - min(window)) < plateau_threshold:
                    log(f"plateau at iter={it} (Δ<{plateau_threshold})"); break
            else:
                consecutive_rej += 1
                if consecutive_rej >= max_consecutive_rejections:
                    log(f"early-stop at iter={it}: {consecutive_rej} consecutive rejections (refiner deadlock at T=0)"); break
    finally:
        if traj_fh is not None:
            traj_fh.close()
    return traj

def run_induction(config_path: pathlib.Path) -> pathlib.Path:
    config = yaml.safe_load(config_path.read_text())
    run_id = _mint_run_id(config)
    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "config.yaml").write_text(yaml.safe_dump(config, sort_keys=False))
    logger = _setup_logger(run_dir)
    logger.info(f"[bold]Induction[/bold] {run_id}")
    client = OllamaClient(model=config["model"]["name"], host=config["model"].get("host", "http://localhost:11434"), max_attempts=config.get("classification", {}).get("max_retries", 3))
    if not client.health_check():
        logger.error("Ollama not reachable."); sys.exit(2)
    all_ex = load_hc3(split=config["data"]["split"], sample_size=None, seed=config["data"].get("seed", 42), min_chars=config["data"].get("min_chars", 32))
    sp = config.get("splits", {})
    splits = make_splits(all_ex, train=sp.get("train", 0.60), val=sp.get("val", 0.20), test=sp.get("test", 0.20), seed=sp.get("seed", 42))
    splits_hash = splits_sha256(splits)
    logger.info(f"splits sha256={splits_hash[:12]}... | train={len(splits['train'])} val={len(splits['val'])} test={len(splits['test'])}")
    train_pool = [all_ex[i] for i in splits["train"]]
    humans = [e for e in train_pool if e.label == LABEL_HUMAN]
    ais = [e for e in train_pool if e.label == LABEL_AI]
    pool = config["seed"]["pool_size"]
    s_half = pool // 2
    seed_ex = humans[:s_half] + ais[: pool - s_half]
    n_val = config["induction"].get("scoring_sample", 200)
    v_half = n_val // 2
    val_ex = humans[s_half : s_half + v_half] + ais[pool - s_half : pool - s_half + (n_val - v_half)]
    if len(val_ex) < n_val:
        logger.warning(f"val_ex shorter than requested ({len(val_ex)} < {n_val}); train pool exhausted")
    logger.info(f"seed={len(seed_ex)} val={len(val_ex)}")
    ind = config.get("induction", {})
    traj = induce(client, seed_ex, val_ex, max_iters=ind.get("max_iters", 30), plateau_threshold=ind.get("plateau_threshold", 0.005), plateau_window=ind.get("plateau_window", 3), misclassified_k=ind.get("misclassified_k", 20), max_consecutive_rejections=ind.get("max_consecutive_rejections", 5), trajectory_file=run_dir / "trajectory.jsonl", logger=logger)
    winner = max(traj, key=lambda s: s.f0_5)
    metrics = {"winner_iter": winner.iter, "f0_5": winner.f0_5, "precision_ai": winner.precision_ai, "recall_ai": winner.recall_ai, "iters_run": len(traj), "accepted_count": sum(1 for s in traj if s.accepted), "splits_sha256": splits_hash, "n_seed": len(seed_ex), "n_val": len(val_ex)}
    (run_dir / "metrics.json").write_text(json.dumps(metrics, indent=2))
    POLICIES_DIR.mkdir(parents=True, exist_ok=True)
    policy_md = POLICIES_DIR / f"{run_id}.md"
    policy_md.write_text(
        f"# Policy {run_id}\n\n"
        f"- F0.5 (val, n={len(val_ex)}): **{winner.f0_5:.4f}** | P(AI): {winner.precision_ai:.4f} | R(AI): {winner.recall_ai:.4f}\n"
        f"- Winner iter: {winner.iter} (parent: {winner.parent_iter}) | model: {config['model']['name']} | seed: {len(seed_ex)}\n"
        f"- Date: {dt.datetime.now().isoformat(timespec='seconds')}\n\n## Policy text\n\n{winner.policy_text}\n"
    )
    RUNS_LOG.parent.mkdir(parents=True, exist_ok=True)
    with RUNS_LOG.open("a") as f:
        f.write(f"| `{run_id}` | {config['model']['name']} | induction / iters={metrics['iters_run']} | F0.5={winner.f0_5:.3f} P={winner.precision_ai:.3f} R={winner.recall_ai:.3f} | {config.get('run', {}).get('notes', '').strip() or 'policy induction'} |\n")
    try:
        plot_path = plot_trajectory(run_dir / "trajectory.jsonl", run_dir / "trajectory.png")
        logger.info(f"Trajectory plot: {plot_path.name}")
    except Exception as e:
        logger.warning(f"Trajectory plot failed: {type(e).__name__}: {e}")
    logger.info(f"[green]Winner[/green] F0.5={winner.f0_5:.3f} iter={winner.iter} → {policy_md}")
    return run_dir

def main() -> None:
    p = argparse.ArgumentParser(prog="aitd-induce")
    p.add_argument("--config", required=True, type=pathlib.Path)
    args = p.parse_args()
    if not args.config.exists():
        Console().print(f"[red]Config not found:[/red] {args.config}"); sys.exit(1)
    run_induction(args.config)

if __name__ == "__main__":
    main()
